# A cronjob for updating nasin-sitelen

name: Cronjob for nasin-sitelen

on:
  schedule:
    - cron: '30 0 * * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Configuration
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --global user.email "AcipenserSturio@users.noreply.github.com"
        git config --global user.name "AcipenserSturio"

    - name: Update nasin-sitelen
      run: |
        cd updating
        python update.py
        cd ..
        git add -A
        git commit -m "Bump for $(date --iso-8601)"
        git push "https://$(GITHUB_TOKEN)@github.com/lipu-linku/nasin-sitelen.git"
