# A cronjob for updating the fonts in ijo/nasinsitelen

name: Cronjob for nasin-sitelen
on:
  schedule:
    - cron: "30 0 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Configuration
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.email "AcipenserSturio@users.noreply.github.com"
          git config --global user.name "AcipenserSturio"
      - name: Update fonts in ijo
        run: |
          python scripts/update_fonts.py  # runs from repo root
          git add nasinsitelen/
          git commit -m "Bump fonts for $(date --iso-8601)"
          git push "https://$(GITHUB_TOKEN)@github.com/lipu-linku/ijo.git"
